name: Android CI
on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.6.0
      
      - name: set up JDK 11
        uses: actions/setup-java@v3.9.0
        with:
          java-version: 11
          distribution: 'corretto'
          cache: gradle
          
      - name: Unit Test
        run: ./gradlew testDebugUnitTest
        
      - name: Android Test Report Action
        uses: asadmansr/android-test-report-action@v1.2.0
        if: ${{ always() }} # IMPORTANT: run Android Test Report regardless
